# .streamlit/secrets.toml
# provide your own api key as optional
OPENAI_API_KEY = "" 

# use the ATLAN_SVC only for testing. This user and following info has limited access to data in Snowflake Dev
[connections.snowpark]
user = "ATLAN_SVC"
password = "Graing3r" 
warehouse = "DMG_WH_M"
role = "ATLAN_SVC"
account = "wwgraingerdev.us-east-1"